spring:
  application:
    name: LibraryAPI
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        libraryapi: trace
    org:
      springframework:
        web: debug